# Datele tale de pe SonarCloud pentru Actomat
sonar.organization=valentin222259
sonar.projectKey=Valentin222259_Actomat-App

# Secretul monorepo-ului: ii spunem sa scaneze ambele foldere!
sonar.sources=actomat-frontend-tailwind/src, actomat-node-backend

# Ignoram folderele inutile pentru ambele proiecte
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.traineddata